### ISSUE TITLE
Support having multiple Play versions to choose from

### ISSUE THREAD

**Issue by maherg** [ikeike443/HudsonPluginForPlay#10]
Having a single Play version defined in the global configuration may be limiting when you have multiple projects using different versions.

**Comment by ikeike443** [comment]
Yes. Exactly.
I'll try to fix it.
Project configuration may be better I think.

**Comment by ikeike443** [comment]
This problem was resolved at 0.0.5 on jenkins update center.
This change as below link has been released. 
https://github.com/ikeike443/HudsonPluginForPlay/commit/59cb490053279ce21843ab7aec3fcbaa9dbcd4d5
