### ISSUE TITLE
Bug suspicion

### ISSUE THREAD

**Issue by ikeike443** [ikeike443/HudsonPluginForPlay#2]
Builder's global.jelly misses its setting after hudson restart?

**Comment by imeredith** [comment]
I see this too, although I thought it was because I was running mvn hpi:run. Will test more tomorrow

**Comment by ikeike443** [comment]
fixed.
https://github.com/ikeike443/HudsonPluginForPlay/commit/a838df24a0c8bac1d90e082fbbb64ab22bd3bed6
