### ISSUE TITLE
Support build parameters in play commands

### ISSUE THREAD

**Issue by cescoffier** [ikeike443/HudsonPluginForPlay#20]
The plugin does not yet support build parameters.

For example, let's imagine we want to build a module (build-module) but the version is defined in the build configuration (in jenkins) and configured when we trigger the job:
So we have a build parameter 'version' and the play command is: build-module --require=1.2.2 --version=${version}

Unfortunately, right now, the ${version} variable is not substituted with the configured value.

**Comment by ikeike443** [comment]
You can configure  the ${version} variable at job property and set a value before kicking job, I think.

**Comment by cescoffier** [comment]
Hi,

Yes you can (and it would be good BTW), but it's more generic like that. You can have any variable you want. (did you check the code I pushed ?)

**Comment by ikeike443** [comment]
Yes I've checked.  
What I wondered about is your saying "Unfortunately, right now, the ${version} variable is not substituted with the configured value.".

Ah..
Did you say, "My code enables to substitute a configured value, so I sent this pull request" ?
If so, it makes sense.

Anyway, thank you very much for your pull request.

**Comment by cescoffier** [comment]
Hi,

Yes, any configured value will be substituted. This is quite generic. So ${version} is just an example. Thanks to have integrated the pull request.
