### ISSUE TITLE
Plugin fails for recent Jenkins version

### ISSUE THREAD

**Issue by eamelink** [ikeike443/HudsonPluginForPlay#32]
Hi,

I've been running this plugin successfully for a while, but suddenly it broke. I think I upgraded to Jenkins 1.434 in the meantime. On another server, also 1.434, I experience the same issue.

This is what is shown in the build log:

```
Executing /home/eamelink/opt/play-1.2.x/play clean "/var/lib/jenkins/jobs/PlayJob/workspace" 
[workspace] $ /home/eamelink/opt/play-1.2.x/play clean /var/lib/jenkins/jobs/PlayJob/workspace
Build step 'Play!' marked build as failure
Finished: FAILURE
```

Previously, it looked like this:

```
play path is /home/eamelink/opt/play-1.2.x/play
Executing /home/eamelink/opt/play-1.2.x/play clean "/var/lib/jenkins/jobs/PlayJob/workspace" 
[workspace] $ /home/eamelink/opt/play-1.2.x/play clean /var/lib/jenkins/jobs/PlayJob/workspace
~        _            _ 
~  _ __ | | __ _ _  _| |
~ | '_ \| |/ _' | || |_|
~ |  __/|_|\____|\__ (_)
~ |_|            |__/   
... etcetera
```

Any clues?

**Comment by ikeike443** [comment]
Thanks,

Which version do you use of play-plugin?

I will check it.
2011/10/20 18:27 "Erik Bakker" <
reply@reply.github.com>:

**Comment by eamelink** [comment]
I am using playframework-plugin version 0.0.12

Thanks in advance!

**Comment by eamelink** [comment]
Well, I think it was my mistake after all, checking the Jenkins logs gives the error:

Cannot run program "~/path/to/play" (in directory "/var/lib/jenkins/jobs/PlayJob/workspace"): java.io.IOException: error=2, No such file or directory

On one server caused by a path starting with ~, on the other server caused by an actual wrong path.

So the immediate problem is solved, but maybe you can catch the exception in PlayAutoTestBuilder.java and display the error in the build logs as well? 

Thanks for your time anyway and great job with the plugin! :)
